services:
  konigsberg:
    build:
      context: .
      dockerfile: konigsberg.dockerfile
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - /data/bingraph-openalex:/influencemap/bingraph-openalex
    environment:
      GUNICORN_CMD_ARGS: --workers 32 --timeout 90 --graceful-timeout 90 --bind 0.0.0.0:8000
  webapp:
    build:
      context: .
      dockerfile: webapp.dockerfile
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      KONIGSBERG_URL: http://konigsberg:8000
      GUNICORN_CMD_ARGS: --workers 32 --timeout 90 --graceful-timeout 90 --bind 0.0.0.0:8000
    depends_on:
      - konigsberg
